name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install pync
          python -m pip install -e .[dev]
      - name: Lint
        run: |
          python -m pip install flake8
          flake8 src tests
      - name: Test
        run: |
          python -m pip install pytest
          pytest
